name: Worker - Deploy Backend

on:
  workflow_call:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Short SHA
        id: meta
        run: echo "SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: backend
          file: backend/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/micuatri-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/micuatri-backend:${{ steps.meta.outputs.SHORT_SHA }}

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.DOCKER_USERNAME }}/micuatri-backend:${{ steps.meta.outputs.SHORT_SHA }}
          containerAppName: micuatri-backend
          resourceGroup: mi-cuatri-rg
          environmentVariables: |
            Google__ClientId=${{ secrets.GOOGLE_CLIENT_ID }}
            Google__ClientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }}
            Google__RedirectUri=${{ secrets.GOOGLE_REDIRECT_URI }}
            ConnectionStrings__MongoDB=${{ secrets.MONGO_CONN_STRING }}
